
### Should give 404
GET http://localhost:3003/

### Get blogs
GET http://localhost:3003/api/blogs

### Post blog
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Testing likes 3",
  "author": "me",
  "url": "http://www.google.com/",
  "likes": 3
}

### Post blog (no likes)
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Testing no likes",
  "author": "me",
  "url": "http://www.google.com/"
}
