
### Should give 404
GET http://localhost:3003/

### Get blogs
GET http://localhost:3003/api/blogs

### Post blog
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Testing likes 3",
  "author": "me",
  "url": "http://www.google.com/",
  "likes": 3
}

### Post blog (no likes)
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Testing no likes",
  "author": "me",
  "url": "http://www.google.com/"
}

### Post blog (missing title)
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "author": "me",
  "url": "http://www.google.com/",
  "likes": 3
}

### Post blog (missing url)
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Testing no likes",
  "author": "me",
  "likes": 3
}

### Delete blog
DELETE http://localhost:3003/api/blogs/5bb0ccd396f32504a49e371d

### Update blog
PUT http://localhost:3003/api/blogs/5bb0e0d5957fe82060a9d447
content-type: application/json

{
  "title": "Testing PUT",
  "author": "me",
  "url": "me@com",
  "likes": 5
}


### Get users
GET http://localhost:3003/api/users

### Create user
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "ttaestaaja",
  "name": "Teppo Testaaja",
  "password": "Sec",
  "adult": false
}
